version: "3.8"
services:
  web-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db-prod
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - HASHING_COST=$HASHING_COST
      - JWT_ACCESS_TOKEN_EXPIRY_TIME=$JWT_ACCESS_TOKEN_EXPIRY_TIME
      - JWT_REFRESH_TOKEN_EXPIRY_TIME=$JWT_REFRESH_TOKEN_EXPIRY_TIME
      - MAXIMUM_PENDING_SENTENCES=$MAXIMUM_PENDING_SENTENCES
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  db-prod:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
      POSTGRES_DB: rocket
    ports:
      - "5432:5432"
    volumes:
      - sentence-base-db:/var/lib/postgresql/data/
volumes:
  sentence-base-db:
