version: "3.1"
services:
  web-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db-prod
  db-prod:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
      POSTGRES_DB: rocket
    ports:
      - "5432:5432"
  db-test:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
    ports:
      - "5430:5432"
